<a href="https://colab.research.google.com/github/frank-morales2020/MLxDL/blob/main/TopAIConcepts.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Top AI Concepts

1. Machine Learning: Core algorithms, statistics, and model training techniques.
2. Deep Learning: Hierarchical neural networks learning complex representations automatically.
3. Neural Networks: Layered architectures efficiently model nonlinear relationships accurately.
4. NLP: Techniques to process and understand natural language text.
5. Computer Vision: Algorithms interpreting and analyzing visual data effectively.
6. Reinforcement Learning: This is about an agent learning to make decisions by interacting with an environment to maximize a reward. Your description, "Distributed traffic across multiple servers for reliability," describes load balancing or distributed systems, not reinforcement learning.
7. Generative Models: Creating new data samples using learned data.
8. LLM (Large Language Models): Generates human-like text using massive pre-trained data.
9. Transformers: Self-attention-based architecture powering modern AI models.
10. Feature Engineering: Designing informative features to improve model performance significantly.
11. Supervised Learning:  This involves learning from labeled data to make predictions or classify outcomes. Your description, "Learns useful representations without labeled data," describes Unsupervised Learning.
12. Bayesian Learning: Incorporate uncertainty using probabilistic model approaches.
13. Prompt Engineering: Crafting effective inputs to guide generative model outputs.

To confirm, are you asking me to provide another AI concept, similar to how I presented "AI Agents," or are you simply acknowledging that you'd like me to continue using that format for future explanations?

Assuming you'd like another concept, let's delve into Prompt Engineering, which is highly relevant for our Gemini 2.0 flight planning AI, especially if it incorporates large language models for communication or decision support.

13. Prompt Engineering: Crafting Effective Inputs to Guide Generative Model Outputs

* Concept Explanation:
Prompt Engineering involves designing and refining inputs (prompts) to generative AI models, such as Large Language Models (LLMs), to elicit desired outputs. For a Gemini 2.0 flight planning AI, this is crucial for several reasons:

* Precise Instructions: We can guide the AI to generate flight plans that adhere to specific regulations, optimize for fuel efficiency, or prioritize safety by providing clear, well-structured prompts.

* Contextual Understanding: By including relevant details about weather, air traffic, aircraft type, and passenger needs in the prompt, the AI can develop a deeper understanding of the flight scenario, leading to more informed decisions.
* Behavioral Control: Techniques like "few-shot prompting" (providing examples) or "chain-of-thought prompting" (asking the model to think step-by-step) can steer the AI's reasoning process and output style, ensuring it generates logical and actionable flight plans.
* Adapting to Scenarios: Prompt engineering allows us to quickly adapt the AI's behavior to new or unusual flight conditions without retraining the entire model, by simply adjusting the prompt.


14. AI Agents: Autonomous systems that perceive, decide, and act.  (This aligns well with our goal of creating an AI agent for flight planning.)
15. Fine-Tuning Models: Customizes pre-trained models for domain-specific tasks.
16. Multimodal Models: Processes and generates across multiple data types like images, videos, and text.
17. Embeddings: Transforms input into machine-readable vector formats.
18. Vector Search: Finds similar items using dense vector embeddings.
19. Model Evaluation: Assessing predictive performance using validation techniques.
20. AI Infrastructure: Deploying scalable systems to support AI operations.
21. Generative Adversarial Networks (GANs)
GANs consist of a generator and a discriminator. The generator creates new data, and the discriminator tries to distinguish between real and generated data.
22. Graph Neural Networks (GNNs)
GNNs operate on graph structures. This example uses a very simplified representation to demonstrate the concept of node features and adjacency. A real GNN would use libraries like PyTorch Geometric or DGL.
23. Causal Inference
Causal inference aims to determine cause-and-effect relationships. This example illustrates the concept of comparing outcomes under different "treatments" (e.g., different flight paths) to infer causality, rather than just correlation.
24. Explainable AI (XAI)
XAI focuses on making AI model decisions understandable to humans. This example conceptually shows how a simple model's "explanation" could be extracted.
25. Federated Learning
Federated Learning allows multiple clients to train a global model collaboratively without sharing their local data. This is a highly conceptual simulation.

Overall, it's a good list of key AI concepts! Just those two corrections for Reinforcement Learning and Supervised Learning were needed.

These examples provide a basic code illustration for each concept. Remember that in a real-world scenario, each of these would involve significantly more complex code, data, and infrastructure, often leveraging specialized libraries and cloud services.

In [1]:
# 1. Machine Learning: Core algorithms, statistics, and model training techniques.

import numpy as np
from sklearn.linear_model import LinearRegression

print("--- 1. Machine Learning: Core Algorithms ---")

# Sample data for a simple linear regression
X = np.array([1, 2, 3, 4, 5]).reshape(-1, 1) # Feature (e.g., hours studied)
y = np.array([2, 4, 5, 4, 5])              # Target (e.g., exam score)

# Create a Linear Regression model
model = LinearRegression()

# Train the model
model.fit(X, y)

# Make a prediction
new_X = np.array([[6]]) # Predict score for 6 hours studied
prediction = model.predict(new_X)

print(f"Features (X):\n{X.flatten()}")
print(f"Target (y):\n{y}")
print(f"Model coefficients: {model.coef_[0]:.2f}")
print(f"Model intercept: {model.intercept_:.2f}")
print(f"Prediction for X=6: {prediction[0]:.2f}\n")

--- 1. Machine Learning: Core Algorithms ---
Features (X):
[1 2 3 4 5]
Target (y):
[2 4 5 4 5]
Model coefficients: 0.60
Model intercept: 2.20
Prediction for X=6: 5.80



In [23]:
import tensorflow as tf
from tensorflow import keras
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
import numpy as np

print("--- 2. Deep Learning: Hierarchical Neural Networks ---")

# Generate some dummy data for a binary classification problem
np.random.seed(42)
X = np.random.rand(100, 10) # 100 samples, 10 features
y = (np.sum(X, axis=1) > 5).astype(int) # Simple classification rule

# Split data into training and test sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Scale features
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

# Build a simple sequential deep learning model
model = keras.Sequential([
    # Use Input layer explicitly as the first layer
    keras.layers.Input(shape=(X_train_scaled.shape[1],)),
    keras.layers.Dense(32, activation='relu'),         # Hidden layer 1
    keras.layers.Dense(16, activation='relu'),         # Hidden layer 2
    keras.layers.Dense(1, activation='sigmoid')        # Output layer
])

# Compile the model
model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])

# Train the model (simplified for demonstration)
print("Training a simple Deep Learning model...")
history = model.fit(X_train_scaled, y_train, epochs=15, batch_size=10, verbose=0) # verbose=0 to suppress output

# Evaluate the model
loss, accuracy = model.evaluate(X_test_scaled, y_test, verbose=0)

print(f"Model trained for 15 epochs.")
print(f"Test Accuracy: {accuracy:.4f}\n")


--- 2. Deep Learning: Hierarchical Neural Networks ---
Training a simple Deep Learning model...
Model trained for 15 epochs.
Test Accuracy: 0.8000



In [27]:
# 3. Neural Networks: Layered Architectures efficiently model nonlinear relationships accurately.

# This example is conceptually similar to Deep Learning (since Deep Learning uses Neural Networks).
# Here, we'll demonstrate a slightly simpler MLP (Multi-Layer Perceptron) without explicit
# mention of "deep" to highlight the core layered architecture.

import numpy as np
from sklearn.neural_network import MLPClassifier
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.datasets import make_classification

print("--- 3. Neural Networks: Layered Architectures ---")

# Generate synthetic dataset for classification
X, y = make_classification(n_samples=100, n_features=10, n_classes=2, random_state=42)

# Split data
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Scale features
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

# Create a Multi-Layer Perceptron (MLP) Classifier
# hidden_layer_sizes defines the number of neurons in each hidden layer.
# (100,) means one hidden layer with 100 neurons.
# Increased max_iter to allow more time for convergence
mlp = MLPClassifier(hidden_layer_sizes=(50, 20), max_iter=500, random_state=42, verbose=False) # Increased from 100

# Train the neural network
print("Training a simple MLP Classifier...")
mlp.fit(X_train_scaled, y_train)

# Evaluate the model
accuracy = mlp.score(X_test_scaled, y_test)

print(f"MLP Classifier trained.")
print(f"Test Accuracy: {accuracy:.4f}\n")

--- 3. Neural Networks: Layered Architectures ---
Training a simple MLP Classifier...
MLP Classifier trained.
Test Accuracy: 0.9500



In [28]:
# 4. NLP: Techniques to process and understand natural language text.

import nltk
from nltk.tokenize import word_tokenize
from collections import Counter

# Ensure necessary NLTK tokenizers are downloaded
try:
    # Attempt to find the required tokenizers
    nltk.data.find('tokenizers/punkt')
    nltk.data.find('tokenizers/punkt_tab') # Check for punkt_tab as well
# Catch the LookupError that occurs if the resource is not found
except LookupError:
    print("Required NLTK tokenizers not found. Downloading...")
    # Download the punkt tokenizer (needed by word_tokenize)
    nltk.download('punkt', quiet=True)
    # Download punkt_tab (needed by sent_tokenize, which word_tokenize uses internally)
    nltk.download('punkt_tab', quiet=True)
    print("Required NLTK tokenizers downloaded.")


print("--- 4. NLP: Natural Language Processing ---")

text = "Natural Language Processing (NLP) is a field of artificial intelligence that focuses on the interaction between computers and human language."

# 1. Tokenization: Breaking text into words or sentences
# The word_tokenize function internally uses sent_tokenize which requires punkt_tab
tokens = word_tokenize(text.lower()) # Convert to lowercase for consistent counting

print(f"Original Text:\n{text}")
print(f"\nWord Tokens:\n{tokens}")

# 2. Frequency Distribution (a simple form of understanding)
word_counts = Counter(tokens)

print(f"\nWord Frequencies:")
for word, count in word_counts.most_common(5): # Show top 5
    print(f"  '{word}': {count}")
print("\n")

--- 4. NLP: Natural Language Processing ---
Original Text:
Natural Language Processing (NLP) is a field of artificial intelligence that focuses on the interaction between computers and human language.

Word Tokens:
['natural', 'language', 'processing', '(', 'nlp', ')', 'is', 'a', 'field', 'of', 'artificial', 'intelligence', 'that', 'focuses', 'on', 'the', 'interaction', 'between', 'computers', 'and', 'human', 'language', '.']

Word Frequencies:
  'language': 2
  'natural': 1
  'processing': 1
  '(': 1
  'nlp': 1




In [29]:
# 5. Computer Vision: Algorithms interpreting and analyzing visual data effectively.

import numpy as np
from PIL import Image # Pillow library for image processing

print("--- 5. Computer Vision: Visual Data Analysis ---")

# Create a dummy 10x10 grayscale image (values 0-255)
# In a real scenario, you would load an image, e.g., Image.open("image.jpg")
dummy_image_array = np.random.randint(0, 256, size=(10, 10), dtype=np.uint8)
dummy_image = Image.fromarray(dummy_image_array, mode='L') # 'L' for grayscale

print(f"Original dummy image (first 3x3 pixels):\n{np.array(dummy_image)[:3, :3]}")

# Example 1: Basic Image Processing - Grayscale Conversion (already grayscale here, so just demonstrate pixel access)
# If it were an RGB image, conversion would involve averaging R, G, B channels.
# For simplicity, let's just invert the pixel values.
inverted_image_array = 255 - dummy_image_array
inverted_image = Image.fromarray(inverted_image_array, mode='L')

print(f"\nInverted dummy image (first 3x3 pixels):\n{np.array(inverted_image)[:3, :3]}")

# Example 2: Simple Feature Extraction (e.g., calculating average pixel intensity)
average_intensity = np.mean(dummy_image_array)
print(f"\nAverage pixel intensity: {average_intensity:.2f}\n")

# Note: For actual CV tasks like object detection or image classification,
# you would use libraries like OpenCV or deep learning frameworks (TensorFlow, PyTorch)
# with pre-trained models. This is a very basic conceptual example.

--- 5. Computer Vision: Visual Data Analysis ---
Original dummy image (first 3x3 pixels):
[[ 46 223 100]
 [186 138  79]
 [ 82   1  38]]

Inverted dummy image (first 3x3 pixels):
[[209  32 155]
 [ 69 117 176]
 [173 254 217]]

Average pixel intensity: 130.31



In [30]:
# 6. Reinforcement Learning: An agent learning to make decisions by interacting with an environment.

# This is a very simplified conceptual example of Q-learning,
# demonstrating the agent-environment interaction loop.

import numpy as np

print("--- 6. Reinforcement Learning: Agent Decision Making ---")

# Define a simple environment (e.g., a 1D grid world)
# States: 0 (start), 1, 2, 3 (goal)
# Actions: 0 (move left), 1 (move right)
# Rewards: +10 for reaching goal, -1 for each step
rewards = np.array([-1, -1, -1, 10]) # Reward for being in state i (reaching goal state 3 gives 10)
# Transition: state + action_effect (0 for left, 1 for right)
# Q-table: rows are states, columns are actions
q_table = np.zeros((4, 2)) # 4 states, 2 actions
learning_rate = 0.8
discount_factor = 0.95
num_episodes = 50

print("Initial Q-table:\n", q_table)

# RL training loop
for episode in range(num_episodes):
    current_state = 0 # Start at state 0
    done = False

    while not done:
        # Choose action (epsilon-greedy policy: explore or exploit)
        if np.random.uniform(0, 1) < 0.1: # 10% chance to explore
            action = np.random.randint(0, 2)
        else: # Exploit
            action = np.argmax(q_table[current_state, :])

        # Execute action and observe next state and reward
        next_state = current_state + (1 if action == 1 else -1)

        # Boundary checks
        if next_state < 0: next_state = 0
        if next_state > 3: next_state = 3

        reward = rewards[next_state] # Reward received upon entering next_state

        # Update Q-value
        # Q(s,a) = Q(s,a) + alpha * (reward + gamma * max(Q(s',a')) - Q(s,a))
        q_table[current_state, action] = q_table[current_state, action] + \
                                         learning_rate * (reward + discount_factor * np.max(q_table[next_state, :]) - q_table[current_state, action])

        current_state = next_state

        if current_state == 3: # Reached goal state
            done = True

print(f"\nQ-table after {num_episodes} episodes of training:\n", np.round(q_table, 2))
print("\n")
# Interpretation: Higher Q-values indicate better (more rewarding) actions from a given state.
# For example, from state 2, moving right (action 1) should have a much higher Q-value than moving left (action 0)
# because it leads to the goal.

--- 6. Reinforcement Learning: Agent Decision Making ---
Initial Q-table:
 [[0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]]

Q-table after 50 episodes of training:
 [[ 5.71  7.07]
 [ 5.66  8.5 ]
 [ 7.06 10.  ]
 [ 0.    0.  ]]




In [9]:
# 7. Generative Models: Creating new data samples using learned data.

# This example demonstrates a very simple text generation using a Markov chain,
# which is a conceptual predecessor to more complex generative models.
# It learns probabilities of sequences and then generates based on them.

from collections import defaultdict
import random

print("--- 7. Generative Models: Creating New Data ---")

# Sample text data to learn from
text = "the quick brown fox jumps over the lazy dog. the dog barks. the fox runs."

# Preprocess the text (simple tokenization)
words = text.lower().replace('.', '').split()

# Build a simple Markov Chain model
# stores: { 'word': [list of words that follow it] }
markov_chain = defaultdict(list)
for i in range(len(words) - 1):
    current_word = words[i]
    next_word = words[i+1]
    markov_chain[current_word].append(next_word)

print(f"Learned Markov Chain (first 3 entries):\n{dict(list(markov_chain.items())[:3])}...")

# Generate new text
def generate_text(model, start_word, length=10):
    generated_sequence = [start_word]
    current_word = start_word

    for _ in range(length - 1):
        if current_word in model and model[current_word]:
            next_word = random.choice(model[current_word])
            generated_sequence.append(next_word)
            current_word = next_word
        else:
            break # No next word found for this sequence

    return ' '.join(generated_sequence)

start_word = random.choice(words) # Pick a random starting word
generated_sentence = generate_text(markov_chain, start_word, length=8)

print(f"\nStarting word for generation: '{start_word}'")
print(f"Generated Text: '{generated_sentence}'\n")

# Real generative models (GANs, VAEs, Diffusion Models) are far more complex,
# learning intricate distributions of data like images, audio, or high-fidelity text.



--- 7. Generative Models: Creating New Data ---
Learned Markov Chain (first 3 entries):
{'the': ['quick', 'lazy', 'dog', 'fox'], 'quick': ['brown'], 'brown': ['fox']}...

Starting word for generation: 'the'
Generated Text: 'the dog the quick brown fox runs'



In [12]:
import json
import asyncio

print("--- 8. LLM: Large Language Models ---")

# Mock LLM API call function
async def mock_llm_generate(prompt):
    """
    Simulates calling an LLM API to generate text.
    In a real application, this would be a network request.
    """
    print(f"Sending prompt to LLM: '{prompt}'")
    # Simulate a delay for API call
    await asyncio.sleep(1)

    # Mock responses based on prompt
    if "Python programming" in prompt:
        return "Python is a high-level, interpreted programming language known for its readability and versatility."
    elif "flight planning" in prompt:
        return "Flight planning involves optimizing routes, considering weather, fuel, and airspace restrictions to ensure a safe and efficient journey."
    else:
        return "As an AI, I can generate text based on various prompts. How can I assist you further?"

# Example usage
async def main():
    user_prompt_1 = "Explain Python programming in one sentence."
    response_1 = await mock_llm_generate(user_prompt_1)
    print(f"LLM Response 1: {response_1}\n")

    user_prompt_2 = "What is involved in flight planning?"
    response_2 = await mock_llm_generate(user_prompt_2)
    print(f"LLM Response 2: {response_2}\n")

print("Simulating LLM interaction...")
await main() # Await the main coroutine directly
print("LLM simulation complete.\n")


--- 8. LLM: Large Language Models ---
Simulating LLM interaction...
Sending prompt to LLM: 'Explain Python programming in one sentence.'
LLM Response 1: Python is a high-level, interpreted programming language known for its readability and versatility.

Sending prompt to LLM: 'What is involved in flight planning?'
LLM Response 2: Flight planning involves optimizing routes, considering weather, fuel, and airspace restrictions to ensure a safe and efficient journey.

LLM simulation complete.



In [13]:
# 9. Transformers: Self-attention-based architecture powering modern AI models.

# This is a highly simplified conceptual representation of the self-attention mechanism,
# which is the core innovation of Transformers.
# A full Transformer implementation involves multiple layers, multi-head attention,
# feed-forward networks, layer normalization, and residual connections.

import numpy as np

print("--- 9. Transformers: Self-Attention Architecture ---")

def softmax(x):
    """Compute softmax values for each row of x."""
    e_x = np.exp(x - np.max(x, axis=-1, keepdims=True))
    return e_x / np.sum(e_x, axis=-1, keepdims=True)

def self_attention(query, key, value, mask=None):
    """
    Simplified self-attention mechanism.
    query, key, value: matrices representing Q, K, V for a single head.
    mask: optional mask for attention (e.g., for causality in decoders).
    """
    # 1. Calculate Attention Scores: Query dot Key transpose
    # (Batch, Seq_len, Features) x (Batch, Features, Seq_len) -> (Batch, Seq_len, Seq_len)
    scores = np.matmul(query, key.T) # No scaling by sqrt(d_k) for simplicity

    # 2. Apply optional mask (e.g., for decoder attention)
    if mask is not None:
        scores = scores + mask # Mask out unwanted connections (e.g., future tokens)

    # 3. Apply Softmax to get Attention Weights
    attention_weights = softmax(scores)

    # 4. Multiply with Value matrix
    output = np.matmul(attention_weights, value)
    return output, attention_weights

# Example usage: Imagine 3 tokens, each with a 4-dimensional embedding
# In reality, Q, K, V are derived from the input embedding via linear transformations.
token_embeddings = np.array([
    [1.0, 0.0, 1.0, 0.0], # "The"
    [0.0, 1.0, 0.0, 1.0], # "cat"
    [1.0, 1.0, 0.0, 0.0]  # "sits"
])

# For self-attention, Q, K, V are all derived from the same input sequence.
# For simplicity, we'll use the embeddings directly as Q, K, V
Q = token_embeddings
K = token_embeddings
V = token_embeddings

print(f"Input Embeddings (Q, K, V):\n{token_embeddings}")

# Calculate self-attention output and weights
output, attention_weights = self_attention(Q, K, V)

print(f"\nSelf-Attention Output:\n{np.round(output, 3)}")
print(f"\nSelf-Attention Weights (how much each token 'attends' to others):\n{np.round(attention_weights, 3)}\n")

# For example, attention_weights[0, 1] indicates how much the first token ("The")
# attends to the second token ("cat").



--- 9. Transformers: Self-Attention Architecture ---
Input Embeddings (Q, K, V):
[[1. 0. 1. 0.]
 [0. 1. 0. 1.]
 [1. 1. 0. 0.]]

Self-Attention Output:
[[0.91  0.335 0.665 0.09 ]
 [0.335 0.91  0.09  0.665]
 [0.788 0.788 0.212 0.212]]

Self-Attention Weights (how much each token 'attends' to others):
[[0.665 0.09  0.245]
 [0.09  0.665 0.245]
 [0.212 0.212 0.576]]



In [31]:
# 10. Feature Engineering: Designing informative features to improve model performance significantly.

import pandas as pd
import numpy as np

print("--- 10. Feature Engineering: Designing Informative Features ---")

# Sample DataFrame with raw features
data = {
    'age': [25, 30, 35, 40, 45],
    'income': [50000, 60000, 75000, 90000, 110000],
    'education_years': [12, 16, 18, 16, 20],
    'has_children': [0, 1, 0, 1, 0]
}
df = pd.DataFrame(data)

print("Original DataFrame:\n", df)

# Example 1: Creating a new feature by combining existing ones (e.g., income per year of education)
df['income_per_education_year'] = df['income'] / df['education_years']

# Example 2: Creating a categorical feature from a numerical one (e.g., age groups)
df['age_group'] = pd.cut(df['age'], bins=[0, 30, 40, np.inf], labels=['young', 'middle_aged', 'senior'])

# Example 3: One-Hot Encoding (for categorical features)
# This isn't generating a new feature from others, but transforming existing for ML models
df_encoded = pd.get_dummies(df, columns=['age_group'], prefix='age_group')


print("\nDataFrame after Feature Engineering:")
print(df_encoded)
print("\n")



--- 10. Feature Engineering: Designing Informative Features ---
Original DataFrame:
    age  income  education_years  has_children
0   25   50000               12             0
1   30   60000               16             1
2   35   75000               18             0
3   40   90000               16             1
4   45  110000               20             0

DataFrame after Feature Engineering:
   age  income  education_years  has_children  income_per_education_year  \
0   25   50000               12             0                4166.666667   
1   30   60000               16             1                3750.000000   
2   35   75000               18             0                4166.666667   
3   40   90000               16             1                5625.000000   
4   45  110000               20             0                5500.000000   

   age_group_young  age_group_middle_aged  age_group_senior  
0             True                  False             False  
1             True  

In [32]:
# 11. Supervised Learning: Learns from labeled data to make predictions or classify outcomes.

# This example uses the Iris dataset for classification, which is a classic supervised learning problem.

from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score

print("--- 11. Supervised Learning: Learning from Labeled Data ---")

# Load the Iris dataset
iris = load_iris()
X = iris.data  # Features (sepal length, sepal width, petal length, petal width)
y = iris.target # Target (species: Setosa, Versicolor, Virginica)

print(f"Features (first 5 samples):\n{X[:5]}")
print(f"Labels (first 5 samples):\n{y[:5]}")
print(f"Target Names: {iris.target_names}\n")

# Split data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)

# Create a Logistic Regression model (a common supervised learning algorithm)
model = LogisticRegression(max_iter=200) # Increase max_iter for convergence warnings

# Train the model using the labeled training data
print("Training Logistic Regression model...")
model.fit(X_train, y_train)

# Make predictions on the test data
y_pred = model.predict(X_test)

# Evaluate the model's performance
accuracy = accuracy_score(y_test, y_pred)

print(f"Model trained on {len(X_train)} samples.")
print(f"Predictions (first 5 test samples): {y_pred[:5]}")
print(f"Actual Labels (first 5 test samples): {y_test[:5]}")
print(f"Accuracy of the model: {accuracy:.4f}\n")



--- 11. Supervised Learning: Learning from Labeled Data ---
Features (first 5 samples):
[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]]
Labels (first 5 samples):
[0 0 0 0 0]
Target Names: ['setosa' 'versicolor' 'virginica']

Training Logistic Regression model...
Model trained on 105 samples.
Predictions (first 5 test samples): [1 0 2 1 1]
Actual Labels (first 5 test samples): [1 0 2 1 1]
Accuracy of the model: 1.0000



In [33]:
# 12. Bayesian Learning: Incorporate uncertainty using probabilistic model approaches.

# This example demonstrates Bayesian inference for a simple coin toss problem.
# We'll estimate the probability of heads (p) given some observed tosses.

import numpy as np
import matplotlib.pyplot as plt
from scipy.stats import beta

print("--- 12. Bayesian Learning: Incorporating Uncertainty ---")

# Prior distribution for the probability of heads (p)
# Using a Beta distribution: Beta(alpha, beta)
# A Beta(1,1) is a uniform prior (all p values equally likely)
alpha_prior = 1
beta_prior = 1

# Observed data: 10 coin tosses, 7 heads (1), 3 tails (0)
coin_tosses = [1, 1, 0, 1, 1, 0, 1, 1, 0, 1]
num_heads = sum(coin_tosses)
num_tails = len(coin_tosses) - num_heads

print(f"Observed data: {len(coin_tosses)} tosses, {num_heads} heads, {num_tails} tails.")

# Update the prior to get the posterior distribution
# For Beta-Binomial conjugacy:
# Posterior alpha = Prior alpha + Number of Heads
# Posterior beta = Prior beta + Number of Tails
alpha_posterior = alpha_prior + num_heads
beta_posterior = beta_prior + num_tails

print(f"Prior: Beta({alpha_prior}, {beta_prior})")
print(f"Posterior: Beta({alpha_posterior}, {beta_posterior})")

# Plotting the prior and posterior distributions (conceptual visualization)
p_values = np.linspace(0, 1, 100) # Possible values for p (probability of heads)
prior_pdf = beta.pdf(p_values, alpha_prior, beta_prior)
posterior_pdf = beta.pdf(p_values, alpha_posterior, beta_posterior)

print("\nVisualizing prior and posterior distributions (conceptual):")
print("  (Imagine a plot where the posterior distribution is narrower and peaked around 0.7)")

# A simple way to report the estimate of p:
# The mean of the Beta posterior distribution is alpha_posterior / (alpha_posterior + beta_posterior)
estimated_p = alpha_posterior / (alpha_posterior + beta_posterior)
print(f"Estimated probability of heads (posterior mean): {estimated_p:.3f}\n")

# plt.figure(figsize=(8, 5))
# plt.plot(p_values, prior_pdf, label=f'Prior Beta({alpha_prior},{beta_prior})')
# plt.plot(p_values, posterior_pdf, label=f'Posterior Beta({alpha_posterior},{beta_posterior})')
# plt.title('Bayesian Inference for Coin Toss')
# plt.xlabel('Probability of Heads (p)')
# plt.ylabel('Probability Density')
# plt.legend()
# plt.grid(True)
# plt.show() # Cannot show plots in this environment, but this is how you'd visualize it.



--- 12. Bayesian Learning: Incorporating Uncertainty ---
Observed data: 10 tosses, 7 heads, 3 tails.
Prior: Beta(1, 1)
Posterior: Beta(8, 4)

Visualizing prior and posterior distributions (conceptual):
  (Imagine a plot where the posterior distribution is narrower and peaked around 0.7)
Estimated probability of heads (posterior mean): 0.667



In [34]:
# 13. Prompt Engineering: Crafting effective inputs to guide generative model outputs.

print("--- 13. Prompt Engineering: Crafting Effective Inputs ---")

# Base instruction for an LLM
base_instruction = "Generate a short story about a brave knight."

# Adding constraints and specific details
# Technique 1: Adding a persona/role
persona_prompt = "Act as a seasoned storyteller. " + base_instruction + " Ensure the story is no more than 100 words and includes a dragon."

# Technique 2: Providing examples (few-shot prompting)
few_shot_example = """
Example:
Input: "Write a haiku about nature."
Output: "Green grass, soft breeze, / Birds sing a sweet melody, / Nature's gentle hug."

Now, "Write a haiku about a bustling city."
"""

# Technique 3: Chain-of-Thought prompting (asking the model to think step-by-step)
cot_prompt = "Let's think step by step. First, outline three key plot points for a detective story. Second, write a brief opening paragraph based on the first plot point."

print(f"Base Prompt:\n'{base_instruction}'\n")
print(f"Prompt with Persona and Constraints:\n'{persona_prompt}'\n")
print(f"Few-Shot Prompt (Conceptual):\n'{few_shot_example}'\n")
print(f"Chain-of-Thought Prompt (Conceptual):\n'{cot_prompt}'\n")

# In a real scenario, these prompts would be sent to an LLM API.
# The effectiveness is judged by the quality and relevance of the LLM's output.



--- 13. Prompt Engineering: Crafting Effective Inputs ---
Base Prompt:
'Generate a short story about a brave knight.'

Prompt with Persona and Constraints:
'Act as a seasoned storyteller. Generate a short story about a brave knight. Ensure the story is no more than 100 words and includes a dragon.'

Few-Shot Prompt (Conceptual):
'
Example:
Input: "Write a haiku about nature."
Output: "Green grass, soft breeze, / Birds sing a sweet melody, / Nature's gentle hug."

Now, "Write a haiku about a bustling city."
'

Chain-of-Thought Prompt (Conceptual):
'Let's think step by step. First, outline three key plot points for a detective story. Second, write a brief opening paragraph based on the first plot point.'



Code Example:
The following Python code illustrates various prompt engineering techniques, such as base instructions, adding persona/roles, few-shot prompting, and chain-of-thought prompting. These examples showcase how different prompt structures can influence the generative model's output

In [49]:
# 13. Prompt Engineering: Crafting effective inputs to guide generative model outputs.

print("--- 13. Prompt Engineering: Crafting Effective Inputs ---")

# Base instruction for an LLM
base_instruction = "Generate a short story about a brave knight."
print(f"Base Prompt:\n'{base_instruction}'\n")

# Adding constraints and specific details
# Technique 1: Adding a persona/role
persona_prompt = "Act as a seasoned storyteller. " + base_instruction + " Ensure the story is no more than 100 words and includes a dragon."
print(f"Prompt with Persona and Constraints:\n'{persona_prompt}'\n")

# Technique 2: Providing examples (few-shot prompting)
few_shot_example = """
Example:
Input: "Write a haiku about nature."
Output: "Green grass, soft breeze, / Birds sing a sweet melody, / Nature's gentle hug."
"""
few_shot_prompt = few_shot_example + "\nNow, \"Write a haiku about a bustling city.\""
print(f"Few-Shot Prompt (Conceptual):\n'{few_shot_prompt}'\n")

# Technique 3: Chain-of-Thought prompting (asking the model to think step-by-step)
cot_prompt = """Let's think step by step. First, outline three key plot points for a detective story. Second, write a brief opening paragraph based on the first plot point."""
print(f"Chain-of-Thought Prompt (Conceptual):\n'{cot_prompt}'\n")

# In a real scenario, these prompts would be sent to an LLM API.
# The effectiveness is judged by the quality and relevance of the LLM's output.

--- 13. Prompt Engineering: Crafting Effective Inputs ---
Base Prompt:
'Generate a short story about a brave knight.'

Prompt with Persona and Constraints:
'Act as a seasoned storyteller. Generate a short story about a brave knight. Ensure the story is no more than 100 words and includes a dragon.'

Few-Shot Prompt (Conceptual):
'
Example:
Input: "Write a haiku about nature."
Output: "Green grass, soft breeze, / Birds sing a sweet melody, / Nature's gentle hug."

Now, "Write a haiku about a bustling city."'

Chain-of-Thought Prompt (Conceptual):
'Let's think step by step. First, outline three key plot points for a detective story. Second, write a brief opening paragraph based on the first plot point.'



In [35]:
# 14. AI Agents: Autonomous systems that perceive, decide, and act.

# This is a simple conceptual model of an AI agent for a "room cleaning" scenario,
# demonstrating the Perceive-Decide-Act cycle.

import time

print("--- 14. AI Agents: Autonomous Systems ---")

class SimpleCleaningAgent:
    def __init__(self, name="Roomba"):
        self.name = name
        self.location = "room_A"
        self.percepts = {}
        self.goal = "clean_room_A"
        self.actions = {
            "move_to_room_B": self._move_to_room_B,
            "vacuum_floor": self._vacuum_floor,
            "report_status": self._report_status
        }
        self.cleaned_rooms = []

    def perceive(self, environment_state):
        """
        Perceives the current state of the environment.
        In a real agent, this would involve sensors, data streams, etc.
        """
        self.percepts = environment_state
        print(f"[{self.name}] Perceiving: {self.percepts}")

    def decide(self):
        """
        Decides the next action based on percepts and internal goals.
        This is the 'brain' of the agent.
        """
        if self.location == "room_A" and not self.percepts.get("room_A_clean"):
            print(f"[{self.name}] Deciding: Room A is dirty, vacuum.")
            return "vacuum_floor"
        elif self.location == "room_A" and self.percepts.get("room_A_clean") and "room_A" not in self.cleaned_rooms:
            print(f"[{self.name}] Deciding: Room A is clean, report.")
            self.cleaned_rooms.append("room_A") # Mark as cleaned
            return "report_status"
        elif self.location == "room_A" and self.percepts.get("room_A_clean") and "room_A" in self.cleaned_rooms and self.percepts.get("room_B_dirty"):
            print(f"[{self.name}] Deciding: Room A is clean, move to Room B.")
            return "move_to_room_B"
        elif self.location == "room_B" and not self.percepts.get("room_B_clean"):
            print(f"[{self.name}] Deciding: Room B is dirty, vacuum.")
            return "vacuum_floor"
        else:
            print(f"[{self.name}] Deciding: Nothing to do or goal reached.")
            return None

    def act(self, action_name):
        """
        Executes the chosen action.
        """
        if action_name and action_name in self.actions:
            print(f"[{self.name}] Acting: Performing '{action_name}'...")
            self.actions[action_name]()
            time.sleep(0.5) # Simulate action time
        elif action_name:
            print(f"[{self.name}] Error: Unknown action '{action_name}'")

    # Private action methods
    def _move_to_room_B(self):
        self.location = "room_B"
        print(f"[{self.name}] Moved to Room B.")

    def _vacuum_floor(self):
        print(f"[{self.name}] Vacuuming floor at {self.location}...")
        # In a real system, this would interact with the environment to change its state.
        # For this demo, we'll simulate the environment state change.

    def _report_status(self):
        print(f"[{self.name}] Reporting: {self.location} is now clean.")


# Simulate an environment
class Environment:
    def __init__(self):
        self.state = {
            "room_A_clean": False,
            "room_B_clean": True, # Initially room B is clean
            "room_B_dirty": False
        }

    def get_state(self):
        return self.state

    def update_state(self, action_performed, agent_location):
        if action_performed == "vacuum_floor" and agent_location == "room_A":
            self.state["room_A_clean"] = True
            print("[Environment] Room A is now clean.")
        if action_performed == "vacuum_floor" and agent_location == "room_B":
            self.state["room_B_clean"] = True
            self.state["room_B_dirty"] = False
            print("[Environment] Room B is now clean.")

# Simulation loop
agent = SimpleCleaningAgent()
env = Environment()

print("\nStarting AI Agent Simulation...")
for i in range(5): # Run for a few steps
    print(f"\n--- Simulation Step {i+1} ---")
    current_env_state = env.get_state()
    agent.perceive(current_env_state)
    chosen_action = agent.decide()
    if chosen_action:
        agent.act(chosen_action)
        env.update_state(chosen_action, agent.location)
    else:
        print(f"[{agent.name}] No action decided. Agent is idle.")
        break
print("\nAI Agent Simulation Ended.\n")



--- 14. AI Agents: Autonomous Systems ---

Starting AI Agent Simulation...

--- Simulation Step 1 ---
[Roomba] Perceiving: {'room_A_clean': False, 'room_B_clean': True, 'room_B_dirty': False}
[Roomba] Deciding: Room A is dirty, vacuum.
[Roomba] Acting: Performing 'vacuum_floor'...
[Roomba] Vacuuming floor at room_A...
[Environment] Room A is now clean.

--- Simulation Step 2 ---
[Roomba] Perceiving: {'room_A_clean': True, 'room_B_clean': True, 'room_B_dirty': False}
[Roomba] Deciding: Room A is clean, report.
[Roomba] Acting: Performing 'report_status'...
[Roomba] Reporting: room_A is now clean.

--- Simulation Step 3 ---
[Roomba] Perceiving: {'room_A_clean': True, 'room_B_clean': True, 'room_B_dirty': False}
[Roomba] Deciding: Nothing to do or goal reached.
[Roomba] No action decided. Agent is idle.

AI Agent Simulation Ended.



In [37]:
# 15. Fine-Tuning Models: Customizes pre-trained models for domain-specific tasks.

# This is a conceptual example of fine-tuning a pre-trained model.
# In practice, fine-tuning involves loading a model trained on a large dataset
# (e.g., ImageNet for computer vision, a large text corpus for NLP)
# and then training it further on a smaller, specific dataset for a new task.

import tensorflow as tf
from tensorflow import keras
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
import numpy as np

print("--- 15. Fine-Tuning Models: Customizing Pre-trained Models ---")

# --- Step 1: Simulate a "Pre-trained Model" ---
# This would typically be a large model like VGG, ResNet, BERT, GPT.
# Here, we'll create a simple dummy "base model".
def create_base_model(input_shape):
    model = keras.Sequential([
        keras.layers.Input(shape=input_shape),
        keras.layers.Dense(128, activation='relu', name='base_dense_1'),
        keras.layers.Dense(64, activation='relu', name='base_dense_2'),
        # This layer might be considered the "feature extractor" output
        keras.layers.Dense(32, activation='relu', name='feature_extractor_output')
    ])
    return model

base_model = create_base_model((10,)) # Dummy input features of 10
base_model.summary(line_length=80)
print("\n(Imagine this is a large model pre-trained on a vast general dataset)\n")

# --- Step 2: Prepare a new, smaller, domain-specific dataset ---
# Let's say we have a small dataset for a specific binary classification task.
np.random.seed(42)
X_new_domain = np.random.rand(50, 10) # 50 samples, 10 features
y_new_domain = (np.sum(X_new_domain[:, :5], axis=1) > 2.5).astype(int) # A specific rule

# Split new domain data
X_train_new, X_test_new, y_train_new, y_test_new = train_test_split(
    X_new_domain, y_new_domain, test_size=0.3, random_state=42)

print(f"New domain dataset: {len(X_new_domain)} samples.")
print(f"New domain training samples: {len(X_train_new)}")
print(f"New domain test samples: {len(X_test_new)}\n")

# --- Step 3: Fine-tuning process ---
# 3a. Freeze the base model's layers (optional but common for initial fine-tuning)
# This prevents the pre-trained weights from changing during early training on new data.
base_model.trainable = False
print("Base model layers frozen (trainable=False).")

# 3b. Add new classification layers on top of the base model
inputs = keras.Input(shape=(10,))
x = base_model(inputs, training=False) # Pass inputs through the frozen base model
outputs = keras.layers.Dense(1, activation='sigmoid', name='classifier_output')(x)
fine_tuned_model = keras.Model(inputs, outputs)

# Compile the new model
fine_tuned_model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])

print("\nFine-tuned model architecture (new layers added on top of frozen base):")
fine_tuned_model.summary(line_length=80)

# 3c. Train only the new layers on the domain-specific data
print("\nTraining (fine-tuning) new layers on domain-specific data for 10 epochs...")
fine_tuned_model.fit(X_train_new, y_train_new, epochs=10, verbose=0)

# 3d. Unfreeze some or all base model layers (optional) and continue training with a lower learning rate
# This allows the pre-trained weights to adapt slightly to the new task.
# fine_tuned_model.trainable = True # Uncomment to unfreeze the base model
# fine_tuned_model.compile(optimizer=keras.optimizers.Adam(1e-5), loss='binary_crossentropy', metrics=['accuracy'])
# fine_tuned_model.fit(X_train_new, y_train_new, epochs=5, verbose=0) # Train for a few more epochs

loss, accuracy = fine_tuned_model.evaluate(X_test_new, y_test_new, verbose=0)
print(f"\nFine-tuning complete.")
print(f"Test Accuracy on new domain data: {accuracy:.4f}\n")



--- 15. Fine-Tuning Models: Customizing Pre-trained Models ---


Model: "sequential_12"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                      ┃ Output Shape             ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ base_dense_1 (Dense)              │ (None, 128)              │         1,408 │
├───────────────────────────────────┼──────────────────────────┼───────────────┤
│ base_dense_2 (Dense)              │ (None, 64)               │         8,256 │
├───────────────────────────────────┼──────────────────────────┼───────────────┤
│ feature_extractor_output (Dense)  │ (None, 32)               │         2,080 │
└───────────────────────────────────┴──────────────────────────┴───────────────┘

 Total params: 11,744 (45.88 KB)

 Trainable params: 11,744 (45.88 KB)

 Non-trainable params: 0 (0.00 B)


(Imagine this is a large model pre-trained on a vast general dataset)

New domain dataset: 50 samples.
New domain training samples: 35
New domain test samples: 15

Base model layers frozen (trainable=False).

Fine-tuned model architecture (new layers added on top of frozen base):


Model: "functional_14"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                      ┃ Output Shape             ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ input_layer_14 (InputLayer)       │ (None, 10)               │             0 │
├───────────────────────────────────┼──────────────────────────┼───────────────┤
│ sequential_12 (Sequential)        │ (None, 32)               │        11,744 │
├───────────────────────────────────┼──────────────────────────┼───────────────┤
│ classifier_output (Dense)         │ (None, 1)                │            33 │
└───────────────────────────────────┴──────────────────────────┴───────────────┘

 Total params: 11,777 (46.00 KB)

 Trainable params: 33 (132.00 B)

 Non-trainable params: 11,744 (45.88 KB)


Training (fine-tuning) new layers on domain-specific data for 10 epochs...

Fine-tuning complete.
Test Accuracy on new domain data: 0.4667



In [38]:
# 16. Multimodal Models: Processes and generates across multiple data types like images, videos, and text.

# This is a conceptual Python example demonstrating how different modalities
# (text and "image features") might be processed and then combined for a task.
# A true multimodal model would involve sophisticated neural networks for each modality
# and complex fusion mechanisms (e.g., cross-attention, shared embeddings).

import numpy as np

print("--- 16. Multimodal Models: Processing Multiple Data Types ---")

# Simulate input data from different modalities
text_input = "a black cat sitting on a white couch"
# Imagine this is a simplified vector representation from an image encoder
image_features_input = np.array([0.8, 0.1, 0.9, 0.2, 0.7]) # e.g., features for "cat", "couch", "black", "white"

print(f"Input Text: '{text_input}'")
print(f"Input Image Features (conceptual): {image_features_input}\n")

# Step 1: Modality-specific processing (conceptual)
# In a real model, this would be a sophisticated text encoder (BERT, GPT)
# and an image encoder (ResNet, Vision Transformer).
def process_text_modality(text):
    # Simulate text embedding (e.g., one-hot, word2vec, BERT embedding)
    # Just a dummy hash-based embedding for illustration
    text_embedding = np.array([len(text), sum(ord(c) for c in text) % 100, len(text.split())])
    print(f"Processed Text Embedding: {text_embedding}")
    return text_embedding

def process_image_modality(image_features):
    # Simulate further processing or just pass through
    print(f"Processed Image Features: {image_features}")
    return image_features

text_processed = process_text_modality(text_input)
image_processed = process_image_modality(image_features_input)

# Step 2: Fusion (combining the processed modalities)
# Common fusion techniques include concatenation, element-wise sum/product, or attention.
def fuse_modalities_simple_concat(text_emb, image_feats):
    # Concatenate the embeddings/features
    fused_representation = np.concatenate((text_emb, image_feats))
    print(f"Fused Representation (Concatenated): {fused_representation}")
    return fused_representation

fused_data = fuse_modalities_simple_concat(text_processed, image_processed)

# Step 3: Downstream task (e.g., classification, generation)
# The fused representation is then fed into a final classifier or decoder.
def multimodal_task_predictor(fused_rep):
    # Simulate a simple prediction based on the fused data
    # E.g., predict if the image contains an animal and an object.
    animal_score = fused_rep[0] + fused_rep[3] # Dummy calculation
    object_score = fused_rep[2] + fused_rep[4] # Dummy calculation
    print(f"\nMultimodal Task Prediction (Conceptual):")
    print(f"  Likelihood of 'animal': {animal_score:.2f}")
    print(f"  Likelihood of 'object': {object_score:.2f}")

multimodal_task_predictor(fused_data)
print("\n")



--- 16. Multimodal Models: Processing Multiple Data Types ---
Input Text: 'a black cat sitting on a white couch'
Input Image Features (conceptual): [0.8 0.1 0.9 0.2 0.7]

Processed Text Embedding: [36  5  8]
Processed Image Features: [0.8 0.1 0.9 0.2 0.7]
Fused Representation (Concatenated): [36.   5.   8.   0.8  0.1  0.9  0.2  0.7]

Multimodal Task Prediction (Conceptual):
  Likelihood of 'animal': 36.80
  Likelihood of 'object': 8.10




In [40]:
# 17. Embeddings: Transforms input into machine-readable vector formats.

# This example demonstrates word embeddings (specifically, using a pre-trained Word2Vec model conceptually).
# Embeddings capture semantic relationships between words.

import numpy as np
# from gensim.models import Word2Vec # Would typically use a library like gensim or spaCy

print("--- 17. Embeddings: Transforming Input into Vectors ---")

# Conceptual pre-trained word embeddings (dummy values for illustration)
# In reality, these are learned from massive text corpora.
word_to_vec_map = {
    "king": np.array([0.1, 0.2, 0.3, 0.4]),
    "queen": np.array([0.15, 0.25, 0.35, 0.45]),
    "man": np.array([0.5, 0.6, 0.7, 0.8]),
    "woman": np.array([0.55, 0.65, 0.75, 0.85]),
    "apple": np.array([0.9, 0.8, 0.7, 0.6]),
    "orange": np.array([0.85, 0.75, 0.65, 0.55]),
    "fruit": np.array([0.88, 0.78, 0.68, 0.58])
}

def get_word_embedding(word):
    """Retrieves the embedding vector for a given word."""
    return word_to_vec_map.get(word.lower(), np.zeros(4)) # Return zeros if word not found

# Example 1: Get embedding for a word
word1 = "king"
embedding1 = get_word_embedding(word1)
print(f"Embedding for '{word1}': {embedding1}")

word2 = "apple"
embedding2 = get_word_embedding(word2)
print(f"Embedding for '{word2}': {embedding2}")

# Example 2: Demonstrate semantic similarity (conceptual)
# Words with similar meanings have similar embeddings (closer in vector space).
# We can use cosine similarity to measure this.
def cosine_similarity(vec1, vec2):
    dot_product = np.dot(vec1, vec2)
    norm_vec1 = np.linalg.norm(vec1)
    norm_vec2 = np.linalg.norm(vec2)
    if norm_vec1 == 0 or norm_vec2 == 0:
        return 0
    return dot_product / (norm_vec1 * norm_vec2)

embedding_king = get_word_embedding("king")
embedding_queen = get_word_embedding("queen")
embedding_man = get_word_embedding("man")
# --- FIX START ---
embedding_apple = get_word_embedding("apple") # Get the embedding for "apple"
# --- FIX END ---
embedding_fruit = get_word_embedding("fruit")

sim_king_queen = cosine_similarity(embedding_king, embedding_queen)
sim_king_man = cosine_similarity(embedding_king, embedding_man)
sim_apple_fruit = cosine_similarity(embedding_apple, embedding_fruit) # Now embedding_apple is defined

print(f"\nCosine Similarity between '{word1}' and 'queen': {sim_king_queen:.3f}")
print(f"Cosine Similarity between '{word1}' and 'man': {sim_king_man:.3f}")
print(f"Cosine Similarity between '{word2}' and 'fruit': {sim_apple_fruit:.3f}\n")

# Notice how 'king' and 'queen' have higher similarity than 'king' and 'man',
# and 'apple' and 'fruit' also have high similarity, demonstrating semantic relationships.

--- 17. Embeddings: Transforming Input into Vectors ---
Embedding for 'king': [0.1 0.2 0.3 0.4]
Embedding for 'apple': [0.9 0.8 0.7 0.6]

Cosine Similarity between 'king' and 'queen': 0.998
Cosine Similarity between 'king' and 'man': 0.969
Cosine Similarity between 'apple' and 'fruit': 1.000



In [41]:
# 18. Vector Search: Finds similar items using dense vector embeddings.

# This example demonstrates a basic vector search using cosine similarity
# to find the most similar items (documents, images, etc.) to a query vector.
# In production, this is often done with specialized vector databases (e.g., Pinecone, Faiss, Weaviate).

import numpy as np

print("--- 18. Vector Search: Finding Similar Items ---")

# Database of items, each represented by a vector embedding
# Item IDs are just indices for simplicity
item_embeddings = {
    "doc1": np.array([0.1, 0.2, 0.3, 0.4]),
    "doc2": np.array([0.15, 0.25, 0.35, 0.45]), # Similar to doc1
    "doc3": np.array([0.8, 0.9, 0.7, 0.6]),
    "doc4": np.array([0.75, 0.85, 0.65, 0.55]), # Similar to doc3
    "doc5": np.array([0.4, 0.3, 0.2, 0.1])      # Different from others
}

print("Available Item Embeddings (conceptual):")
for item, emb in item_embeddings.items():
    print(f"  {item}: {emb}")

def cosine_similarity(vec1, vec2):
    dot_product = np.dot(vec1, vec2)
    norm_vec1 = np.linalg.norm(vec1)
    norm_vec2 = np.linalg.norm(vec2)
    if norm_vec1 == 0 or norm_vec2 == 0:
        return 0
    return dot_product / (norm_vec1 * norm_vec2)

def vector_search(query_vector, item_embeddings, top_k=3):
    """
    Performs a simple vector search to find top_k most similar items.
    """
    similarities = []
    for item_id, item_vec in item_embeddings.items():
        sim = cosine_similarity(query_vector, item_vec)
        similarities.append((item_id, sim))

    # Sort by similarity in descending order
    similarities.sort(key=lambda x: x[1], reverse=True)

    return similarities[:top_k]

# Example Query: A query vector for something similar to doc1/doc2
query_vector = np.array([0.12, 0.22, 0.32, 0.42])

print(f"\nQuery Vector: {query_vector}")

# Perform vector search
results = vector_search(query_vector, item_embeddings, top_k=2)

print(f"\nTop 2 similar items to the query:")
for item_id, sim in results:
    print(f"  Item: {item_id}, Similarity: {sim:.3f}")
print("\n")



--- 18. Vector Search: Finding Similar Items ---
Available Item Embeddings (conceptual):
  doc1: [0.1 0.2 0.3 0.4]
  doc2: [0.15 0.25 0.35 0.45]
  doc3: [0.8 0.9 0.7 0.6]
  doc4: [0.75 0.85 0.65 0.55]
  doc5: [0.4 0.3 0.2 0.1]

Query Vector: [0.12 0.22 0.32 0.42]

Top 2 similar items to the query:
  Item: doc1, Similarity: 1.000
  Item: doc2, Similarity: 0.999




In [42]:
# 19. Model Evaluation: Assessing predictive performance using validation techniques.

# This example demonstrates basic model evaluation metrics for a binary classification problem:
# Accuracy, Precision, Recall, and F1-score.

from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score
import numpy as np

print("--- 19. Model Evaluation: Assessing Predictive Performance ---")

# Simulate true labels and predicted labels from a binary classification model
# True labels (what actually happened)
y_true = np.array([1, 0, 1, 1, 0, 1, 0, 0, 1, 0])
# Predicted labels (what the model predicted)
y_pred = np.array([1, 1, 1, 0, 0, 1, 0, 1, 1, 0])

print(f"True Labels (y_true): {y_true}")
print(f"Predicted Labels (y_pred): {y_pred}\n")

# Calculate common evaluation metrics:

# Accuracy: (TP + TN) / (TP + TN + FP + FN)
# The proportion of correctly classified instances.
accuracy = accuracy_score(y_true, y_pred)
print(f"Accuracy: {accuracy:.3f}")

# Precision: TP / (TP + FP)
# Of all instances predicted as positive, how many were actually positive.
precision = precision_score(y_true, y_pred)
print(f"Precision (for positive class 1): {precision:.3f}")

# Recall (Sensitivity): TP / (TP + FN)
# Of all actual positive instances, how many were correctly identified.
recall = recall_score(y_true, y_pred)
print(f"Recall (for positive class 1): {recall:.3f}")

# F1-Score: 2 * (Precision * Recall) / (Precision + Recall)
# The harmonic mean of precision and recall, balancing both.
f1 = f1_score(y_true, y_pred)
print(f"F1-Score (for positive class 1): {f1:.3f}\n")

# For multi-class classification, you might use 'macro', 'micro', or 'weighted' averages.
# Other metrics include ROC AUC, Confusion Matrix, MSE (for regression), etc.



--- 19. Model Evaluation: Assessing Predictive Performance ---
True Labels (y_true): [1 0 1 1 0 1 0 0 1 0]
Predicted Labels (y_pred): [1 1 1 0 0 1 0 1 1 0]

Accuracy: 0.700
Precision (for positive class 1): 0.667
Recall (for positive class 1): 0.800
F1-Score (for positive class 1): 0.727



In [43]:
# 20. AI Infrastructure: Deploying scalable systems to support AI operations.

# This is a conceptual Python script outlining typical steps in deploying an AI model.
# In a real-world scenario, this would involve cloud services (AWS, GCP, Azure),
# Docker/Kubernetes, CI/CD pipelines, MLOps tools (MLflow, Kubeflow),
# monitoring systems, and API gateways.

print("--- 20. AI Infrastructure: Deploying Scalable Systems ---")

# --- Step 1: Model Export/Serialization ---
# After training, the model needs to be saved in a deployable format.
def export_model(model_object, path="model.pkl"):
    print(f"Exporting trained model to: {path} (e.g., using pickle, ONNX, TensorFlow SavedModel)")
    # Example: model_object.save(path) for TensorFlow/Keras
    # Example: pickle.dump(model_object, open(path, 'wb')) for scikit-learn
    print("Model exported successfully.")

# Simulate a trained model object
class DummyTrainedModel:
    def predict(self, data):
        return [0.7, 0.3] # Dummy prediction

trained_model = DummyTrainedModel()
export_model(trained_model, "my_classification_model.h5") # Example path for Keras


# --- Step 2: Containerization (e.g., Docker) ---
# Packaging the model, its dependencies, and serving code into a portable unit.
def create_dockerfile_concept():
    print("\nCreating conceptual Dockerfile:")
    dockerfile_content = """
    # Use a lightweight Python base image
    FROM python:3.9-slim-buster

    # Set working directory
    WORKDIR /app

    # Copy dependencies file
    COPY requirements.txt .

    # Install Python dependencies
    RUN pip install --no-cache-dir -r requirements.txt

    # Copy the exported model and application code
    COPY my_classification_model.h5 .
    COPY app.py .

    # Expose the port the application will run on
    EXPOSE 8080

    # Command to run the application
    CMD ["python", "app.py"]
    """
    # In reality, this would write to a Dockerfile
    print(dockerfile_content)
    print("Dockerfile concept generated.")

create_dockerfile_concept()

# --- Step 3: Deployment (e.g., Kubernetes, serverless) ---
# Orchestrating the containerized application for scalability and reliability.
def deploy_to_cloud_concept(service_name="my-ai-service"):
    print(f"\nConceptual Deployment to Cloud (e.g., Kubernetes/GKE, Cloud Run, AWS SageMaker):")
    print(f"  1. Build Docker image: `docker build -t {service_name}:latest .`")
    print(f"  2. Push image to container registry: `docker push gcr.io/my-project/{service_name}:latest`")
    print(f"  3. Deploy to orchestrator/serverless platform (e.g., Kubernetes deployment YAML):")
    deployment_yaml_concept = f"""
    apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: {service_name}-deployment
    spec:
      replicas: 3 # Scale across 3 instances
      selector:
        matchLabels:
          app: {service_name}
      template:
        metadata:
          labels:
            app: {service_name}
        spec:
          containers:
          - name: {service_name}-container
            image: gcr.io/my-project/{service_name}:latest
            ports:
            - containerPort: 8080
    """
    print(deployment_yaml_concept)
    print(f"  {service_name} deployed (conceptually).")

deploy_to_cloud_concept()

# --- Step 4: Monitoring and Logging ---
# Essential for observing model performance, resource usage, and errors in production.
def conceptual_monitoring():
    print("\nConceptual Monitoring and Logging:")
    print("  - Integrate with Prometheus/Grafana for metrics.")
    print("  - Use Cloud Logging/ELK stack for centralized logs.")
    print("  - Set up alerts for model drift, error rates, and latency spikes.")

conceptual_monitoring()

print("\nAI Infrastructure setup (conceptual) complete.\n")



--- 20. AI Infrastructure: Deploying Scalable Systems ---
Exporting trained model to: my_classification_model.h5 (e.g., using pickle, ONNX, TensorFlow SavedModel)
Model exported successfully.

Creating conceptual Dockerfile:

    # Use a lightweight Python base image
    FROM python:3.9-slim-buster

    # Set working directory
    WORKDIR /app

    # Copy dependencies file
    COPY requirements.txt .

    # Install Python dependencies
    RUN pip install --no-cache-dir -r requirements.txt

    # Copy the exported model and application code
    COPY my_classification_model.h5 .
    COPY app.py .

    # Expose the port the application will run on
    EXPOSE 8080

    # Command to run the application
    CMD ["python", "app.py"]
    
Dockerfile concept generated.

Conceptual Deployment to Cloud (e.g., Kubernetes/GKE, Cloud Run, AWS SageMaker):
  1. Build Docker image: `docker build -t my-ai-service:latest .`
  2. Push image to container registry: `docker push gcr.io/my-project/my-ai-servi

In [44]:
import numpy as np
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import layers

print("--- 21. Generative Adversarial Networks (GANs) ---")

# --- Step 1: Define the Generator ---
# The generator takes random noise as input and tries to produce data similar to the training data.
def build_generator(latent_dim):
    model = keras.Sequential([
        layers.Dense(128, activation="relu", input_shape=(latent_dim,)),
        layers.BatchNormalization(),
        layers.Dense(256, activation="relu"),
        layers.BatchNormalization(),
        layers.Dense(784, activation="sigmoid") # e.g., for generating flattened 28x28 images
    ], name="generator")
    return model

# --- Step 2: Define the Discriminator ---
# The discriminator takes data (real or fake) as input and tries to classify it as real or fake.
def build_discriminator(img_shape):
    model = keras.Sequential([
        layers.Dense(256, activation="relu", input_shape=img_shape),
        layers.Dropout(0.3),
        layers.Dense(128, activation="relu"),
        layers.Dropout(0.3),
        layers.Dense(1, activation="sigmoid") # Binary classification (real/fake)
    ], name="discriminator")
    return model

# --- Step 3: Compile the Discriminator ---
discriminator_optimizer = keras.optimizers.Adam(learning_rate=0.0002, beta_1=0.5)
discriminator = build_discriminator(img_shape=(784,))
discriminator.compile(optimizer=discriminator_optimizer, loss="binary_crossentropy", metrics=["accuracy"])

# --- Step 4: Define the GAN (Generator + Discriminator) ---
# The GAN model trains the generator by keeping the discriminator's weights frozen.
latent_dim = 100
generator = build_generator(latent_dim)
discriminator.trainable = False # Discriminator is not trained during GAN compilation

gan_input = keras.Input(shape=(latent_dim,))
fake_img = generator(gan_input)
gan_output = discriminator(fake_img)
gan = keras.Model(gan_input, gan_output, name="gan")

gan_optimizer = keras.optimizers.Adam(learning_rate=0.0002, beta_1=0.5)
gan.compile(optimizer=gan_optimizer, loss="binary_crossentropy")

print("\nConceptual GAN Setup:")
generator.summary(line_length=80)
discriminator.summary(line_length=80)
gan.summary(line_length=80)

print("\n(In a real scenario, you would train these models iteratively. "
      "Here, we just set up the architecture.)")

# Example: Generate a dummy image from noise
dummy_noise = np.random.rand(1, latent_dim)
generated_image = generator.predict(dummy_noise)
print(f"\nExample generated data (first 10 pixels): {generated_image[0, :10].round(2)}")

--- 21. Generative Adversarial Networks (GANs) ---


/usr/local/lib/python3.11/dist-packages/keras/src/layers/core/dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)



Conceptual GAN Setup:


Model: "generator"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                      ┃ Output Shape             ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense_36 (Dense)                  │ (None, 128)              │        12,928 │
├───────────────────────────────────┼──────────────────────────┼───────────────┤
│ batch_normalization               │ (None, 128)              │           512 │
│ (BatchNormalization)              │                          │               │
├───────────────────────────────────┼──────────────────────────┼───────────────┤
│ dense_37 (Dense)                  │ (None, 256)              │        33,024 │
├───────────────────────────────────┼──────────────────────────┼───────────────┤
│ batch_normalization_1             │ (None, 256)              │         1,024 │
│ (BatchNormalization)              │                          │               │
├───────────────────────────────────┼──────────────────────────┼───────────────┤
│ dense_38 (Dense)                  │ (None, 784)              │       201,488 │
└───────────────────────────────────┴──────────────────────────┴───────────────┘

 Total params: 248,976 (972.56 KB)

 Trainable params: 248,208 (969.56 KB)

 Non-trainable params: 768 (3.00 KB)

Model: "discriminator"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                      ┃ Output Shape             ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense_33 (Dense)                  │ (None, 256)              │       200,960 │
├───────────────────────────────────┼──────────────────────────┼───────────────┤
│ dropout (Dropout)                 │ (None, 256)              │             0 │
├───────────────────────────────────┼──────────────────────────┼───────────────┤
│ dense_34 (Dense)                  │ (None, 128)              │        32,896 │
├───────────────────────────────────┼──────────────────────────┼───────────────┤
│ dropout_1 (Dropout)               │ (None, 128)              │             0 │
├───────────────────────────────────┼──────────────────────────┼───────────────┤
│ dense_35 (Dense)                  │ (None, 1)                │           129 │
└───────────────────────────────────┴──────────────────────────┴───────────────┘

 Total params: 233,985 (914.00 KB)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 233,985 (914.00 KB)

Model: "gan"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                      ┃ Output Shape             ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ input_layer_17 (InputLayer)       │ (None, 100)              │             0 │
├───────────────────────────────────┼──────────────────────────┼───────────────┤
│ generator (Sequential)            │ (None, 784)              │       248,976 │
├───────────────────────────────────┼──────────────────────────┼───────────────┤
│ discriminator (Sequential)        │ (None, 1)                │       233,985 │
└───────────────────────────────────┴──────────────────────────┴───────────────┘

 Total params: 482,961 (1.84 MB)

 Trainable params: 248,208 (969.56 KB)

 Non-trainable params: 234,753 (917.00 KB)


(In a real scenario, you would train these models iteratively. Here, we just set up the architecture.)
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 160ms/step

Example generated data (first 10 pixels): [0.52 0.48 0.5  0.45 0.48 0.49 0.47 0.52 0.54 0.52]


In [45]:
import numpy as np

print("--- 22. Graph Neural Networks (GNNs) ---")

# --- Step 1: Define a simple graph (adjacency matrix) ---
# Represents connections between nodes (e.g., airports, waypoints)
# A[i,j] = 1 if node i is connected to node j, 0 otherwise
adjacency_matrix = np.array([
    [0, 1, 1, 0], # Node 0 connected to Node 1, Node 2
    [1, 0, 1, 1], # Node 1 connected to Node 0, Node 2, Node 3
    [1, 1, 0, 0], # Node 2 connected to Node 0, Node 1
    [0, 1, 0, 0]  # Node 3 connected to Node 1
])
print("Adjacency Matrix (Connections):\n", adjacency_matrix)

# --- Step 2: Define Node Features ---
# Represents properties of each node (e.g., airport capacity, weather at waypoint)
# Here, 2 features per node for simplicity
node_features = np.array([
    [0.1, 0.2], # Node 0 features
    [0.5, 0.3], # Node 1 features
    [0.8, 0.6], # Node 2 features
    [0.2, 0.9]  # Node 3 features
])
print("\nInitial Node Features:\n", node_features)

# --- Step 3: Conceptual Graph Convolution Operation ---
# A very simplified idea of how information propagates.
# In a real GNN, this involves learnable weight matrices and aggregation functions.
# Here, we'll simply sum features of neighbors for each node.
def simple_graph_convolution(features, adj_matrix):
    # Multiply features by adjacency matrix to aggregate neighbor features
    # (conceptually, not true matrix multiplication for aggregation here)
    aggregated_features = np.dot(adj_matrix, features)
    return aggregated_features

# Apply a conceptual graph convolution
updated_node_features = simple_graph_convolution(node_features, adjacency_matrix)

print("\nUpdated Node Features (after conceptual graph convolution):\n", np.round(updated_node_features, 2))
print("(This demonstrates how information from neighbors could influence a node's representation.)")

# --- Conceptual Application for Flight Planning ---
print("\nConceptual GNN Application for Flight Planning:")
print("- Nodes could be airports, waypoints, or airspace sectors.")
print("- Edges could represent flight paths or permissible transitions.")
print("- Node features could be weather conditions, airport congestion, or fuel prices.")
print("- GNNs could learn optimal routes by considering the interconnectedness and features of the entire network.")

--- 22. Graph Neural Networks (GNNs) ---
Adjacency Matrix (Connections):
 [[0 1 1 0]
 [1 0 1 1]
 [1 1 0 0]
 [0 1 0 0]]

Initial Node Features:
 [[0.1 0.2]
 [0.5 0.3]
 [0.8 0.6]
 [0.2 0.9]]

Updated Node Features (after conceptual graph convolution):
 [[1.3 0.9]
 [1.1 1.7]
 [0.6 0.5]
 [0.5 0.3]]
(This demonstrates how information from neighbors could influence a node's representation.)

Conceptual GNN Application for Flight Planning:
- Nodes could be airports, waypoints, or airspace sectors.
- Edges could represent flight paths or permissible transitions.
- Node features could be weather conditions, airport congestion, or fuel prices.
- GNNs could learn optimal routes by considering the interconnectedness and features of the entire network.


In [46]:
import numpy as np
import pandas as pd
from scipy.stats import ttest_ind

print("--- 23. Causal Inference ---")

# --- Conceptual Scenario: Impact of two different flight paths on delay ---
# Imagine two flight paths (Path A and Path B) used for similar routes.
# We want to know if one *causes* more delays than the other.

# Simulate data for two groups (e.g., flights that took Path A vs. Path B)
np.random.seed(42)
flights_path_A = np.random.normal(loc=10, scale=3, size=100)  # Delays in minutes for Path A
flights_path_B = np.random.normal(loc=12, scale=3.5, size=100) # Delays in minutes for Path B

# Introduce a "causal" factor for Path B (e.g., frequent unexpected ATC holds)
# This isn't statistically rigorous causal inference, but conceptual
flights_path_B += np.random.choice([0, 5, 10], size=100, p=[0.7, 0.2, 0.1]) # 30% of Path B flights get extra delay

df_causal = pd.DataFrame({
    'Flight_ID': range(200),
    'Path_Taken': ['A'] * 100 + ['B'] * 100,
    'Delay_Minutes': np.concatenate([flights_path_A, flights_path_B])
})

print("Conceptual Flight Data (first 5 rows):\n", df_causal.head())
print("\nMean delay for Path A:", np.mean(df_causal[df_causal['Path_Taken'] == 'A']['Delay_Minutes']).round(2))
print("Mean delay for Path B:", np.mean(df_causal[df_causal['Path_Taken'] == 'B']['Delay_Minutes']).round(2))

# --- Conceptual A/B Test (Randomized Controlled Trial analogy) ---
# If we could randomly assign flights to Path A or Path B, then a difference in means
# could imply causality. In real life, flights are not randomly assigned.
stat, p_value = ttest_ind(df_causal[df_causal['Path_Taken'] == 'A']['Delay_Minutes'],
                          df_causal[df_causal['Path_Taken'] == 'B']['Delay_Minutes'])

print(f"\nConceptual T-test result: p-value = {p_value:.3f}")
if p_value < 0.05:
    print(" (A statistically significant difference suggests Path B might be *causing* more delays.)")
else:
    print(" (No statistically significant difference observed.)")

print("\n(True causal inference often requires more advanced techniques like "
      "matching, instrumental variables, or deep learning-based causal models to "
      "account for confounding factors in observational data.)")

--- 23. Causal Inference ---
Conceptual Flight Data (first 5 rows):
    Flight_ID Path_Taken  Delay_Minutes
0          0          A      11.490142
1          1          A       9.585207
2          2          A      11.943066
3          3          A      14.569090
4          4          A       9.297540

Mean delay for Path A: 9.69
Mean delay for Path B: 13.63

Conceptual T-test result: p-value = 0.000
 (A statistically significant difference suggests Path B might be *causing* more delays.)

(True causal inference often requires more advanced techniques like matching, instrumental variables, or deep learning-based causal models to account for confounding factors in observational data.)


In [47]:
import numpy as np
from sklearn.linear_model import LogisticRegression

print("--- 24. Explainable AI (XAI) ---")

# --- Conceptual Scenario: Explaining a flight delay prediction ---
# Imagine a simple model that predicts flight delay based on a few factors.

# Sample data: [Temperature_Deviation, Wind_Speed_Deviation, Airspace_Congestion_Index]
X_features = np.array([
    [2, 10, 0.8], # Flight 1: some temp, high wind, high congestion
    [-1, 5, 0.2], # Flight 2: lower temp, low wind, low congestion
    [5, 15, 0.9], # Flight 3: high temp, very high wind, very high congestion
    [0, 2, 0.1]   # Flight 4: normal temp, low wind, very low congestion
])
# Target: 1 for delayed, 0 for on-time
y_labels = np.array([1, 0, 1, 0])

feature_names = ["Temp_Deviation", "Wind_Speed_Deviation", "Airspace_Congestion"]

# Train a simple Logistic Regression model (an inherently more interpretable model)
model_xai = LogisticRegression()
model_xai.fit(X_features, y_labels)

print("Simple Logistic Regression Model trained for delay prediction.")
print("Model Coefficients (Feature Importance):\n", model_xai.coef_[0].round(2))
print(f"  {feature_names[0]}: {model_xai.coef_[0][0]:.2f}")
print(f"  {feature_names[1]}: {model_xai.coef_[0][1]:.2f}")
print(f"  {feature_names[2]}: {model_xai.coef_[0][2]:.2f}")

# --- Conceptual Explanation for a specific prediction ---
# For Logistic Regression, coefficients can be seen as a form of explanation.
# Larger positive coefficients mean that feature contributes more to the positive class (delay).
sample_flight_features = np.array([[3, 12, 0.7]]) # A new flight
predicted_delay = model_xai.predict(sample_flight_features)[0]
predicted_prob = model_xai.predict_proba(sample_flight_features)[0, 1]

print(f"\nPredicting for a new flight with features: {sample_flight_features[0]}")
print(f"Predicted Delay (1=Yes, 0=No): {predicted_delay}")
print(f"Predicted Probability of Delay: {predicted_prob:.2f}")

print("\nConceptual Explanation (based on feature importance for this simple model):")
print(f"The model predicted a delay due to a combination of factors. "
      f"Specifically, 'Wind_Speed_Deviation' (coefficient {model_xai.coef_[0][1]:.2f}) "
      f"and 'Airspace_Congestion' (coefficient {model_xai.coef_[0][2]:.2f}) "
      f"had the strongest positive influence on the prediction of delay.")

print("\n(For complex models like Deep Neural Networks, XAI techniques like "
      "LIME, SHAP, or attention mechanisms are used to provide more granular explanations.)")

--- 24. Explainable AI (XAI) ---
Simple Logistic Regression Model trained for delay prediction.
Model Coefficients (Feature Importance):
 [0.33 0.65 0.07]
  Temp_Deviation: 0.33
  Wind_Speed_Deviation: 0.65
  Airspace_Congestion: 0.07

Predicting for a new flight with features: [ 3.  12.   0.7]
Predicted Delay (1=Yes, 0=No): 1
Predicted Probability of Delay: 0.98

Conceptual Explanation (based on feature importance for this simple model):
The model predicted a delay due to a combination of factors. Specifically, 'Wind_Speed_Deviation' (coefficient 0.65) and 'Airspace_Congestion' (coefficient 0.07) had the strongest positive influence on the prediction of delay.

(For complex models like Deep Neural Networks, XAI techniques like LIME, SHAP, or attention mechanisms are used to provide more granular explanations.)


In [48]:
import numpy as np

print("--- 25. Federated Learning (Conceptual) ---")

# --- Conceptual Scenario: Multiple airlines contributing to a global flight delay model ---
# Each "client" (airline) has its own local dataset and trains a local model.
# A central server aggregates these local models to create a better global model.

# Step 1: Simulate initial global model weights (simplified as a single number)
global_model_weight = 0.5
print(f"Initial Global Model Weight: {global_model_weight:.2f}")

# Step 2: Simulate local data and local model training for multiple clients
num_clients = 3
client_local_data_impacts = [0.1, 0.8, -0.2] # Simulate how each client's data would 'shift' the weight

print("\n--- Federated Learning Rounds ---")
num_rounds = 3
for round_num in range(1, num_rounds + 1):
    print(f"\nRound {round_num}:")
    local_model_updates = []
    for i in range(num_clients):
        # Simulate local training: client updates model based on its data
        # For simplicity, let's say client adjusts the global weight based on its 'impact'
        local_model_weight = global_model_weight + client_local_data_impacts[i] * 0.1 * np.random.rand()
        local_model_updates.append(local_model_weight)
        print(f"  Client {i+1} trains locally, resulting in local weight: {local_model_weight:.2f}")

    # Step 3: Central Server Aggregation (e.g., averaging local model updates)
    new_global_model_weight = np.mean(local_model_updates)
    print(f"Central server aggregates local weights. New Global Model Weight: {new_global_model_weight:.2f}")
    global_model_weight = new_global_model_weight

print("\n--- Federated Learning Complete ---")
print(f"Final Global Model Weight: {global_model_weight:.2f}")

print("\n(This is a highly simplified illustration. Real federated learning involves "
      "complex aggregation algorithms, secure multi-party computation, and communication protocols.)")

--- 25. Federated Learning (Conceptual) ---
Initial Global Model Weight: 0.50

--- Federated Learning Rounds ---

Round 1:
  Client 1 trains locally, resulting in local weight: 0.51
  Client 2 trains locally, resulting in local weight: 0.53
  Client 3 trains locally, resulting in local weight: 0.48
Central server aggregates local weights. New Global Model Weight: 0.51

Round 2:
  Client 1 trains locally, resulting in local weight: 0.52
  Client 2 trains locally, resulting in local weight: 0.52
  Client 3 trains locally, resulting in local weight: 0.51
Central server aggregates local weights. New Global Model Weight: 0.51

Round 3:
  Client 1 trains locally, resulting in local weight: 0.52
  Client 2 trains locally, resulting in local weight: 0.52
  Client 3 trains locally, resulting in local weight: 0.51
Central server aggregates local weights. New Global Model Weight: 0.51

--- Federated Learning Complete ---
Final Global Model Weight: 0.51

(This is a highly simplified illustration. 